<!DOCTYPE html>
<html lang="fa">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>by hpishin06 on github!</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<style>body{font-family:'Arial',sans-serif;background:linear-gradient(to bottom,#00bcd4,#009688);color:#fff;text-align:center;padding:0;margin:0;}
h1{color:#fff;margin-bottom:30px;}.container{display:grid;grid-template-columns:repeat(4,1fr);grid-template-rows:repeat(2,1fr);gap:20px;max-width:1200px;margin:0 auto;padding:20px;}.card{background-color:#fff;border-radius:15px;box-shadow:0 4px 10px rgba(0,0,0,0.1);padding:30px;text-align:center;position:relative;height:200px;display:flex;justify-content:center;align-items:center;flex-direction:column;transition:all 0.3s ease-in-out;}.card:hover{background-color:#e0f7fa;transform:scale(1.05);}.card i{font-size:40px;margin-bottom:10px;color:#009688;}.card h3{color:#333;font-size:20px;margin-bottom:10px;}.price{font-size:24px;font-weight:bold;color:#28a745;}::-webkit-scrollbar{display:none;}.currency-symbol{font-size:28px;margin-top:10px;}.header{background-color:#333;color:#fff;padding:15px;position:fixed;width:100%;top:0;left:0;z-index:1000;transition:top 0.3s;}.hidden{top:-100px;}.content{margin-top:120px;}</style></head>
<body><div class="content">
<div class="container">
<div class="card" id="usd"><i class="fas fa-dollar-sign"></i><h3>دلار</h3><div class="price">Loading...</div><div class="currency-symbol">USD</div></div>
<div class="card" id="eur"><i class="fas fa-euro-sign"></i><h3>یورو</h3><div class="price">Loading...</div><div class="currency-symbol">€</div></div>
<div class="card" id="tty"><i class="fa-solid fa-turkish-lira-sign"></i><h3>لیر ترکیه</h3><div class="price">Loading...</div><div class="currency-symbol">TTY</div></div>
<div class="card" id="gold_coin"><i class="fas fa-coins"></i><h3>سکه بهار آزادی</h3><div class="price">Loading...</div><div class="currency-symbol">تومان</div></div>
<div class="card" id="half_coin"><i class="fas fa-coins"></i><h3>نیم سکه</h3><div class="price">Loading...</div><div class="currency-symbol">تومان</div></div>
<div class="card" id="quarter_coin"><i class="fas fa-coins"></i><h3>ربع سکه</h3><div class="price">Loading...</div><div class="currency-symbol">تومان</div></div>
<div class="card" id="imami_coin"><i class="fas fa-coins"></i><h3>سکه امامی</h3><div class="price">Loading...</div><div class="currency-symbol">تومان</div></div>
<div class="card" id="gram_coin"><i class="fas fa-coins"></i><h3>سکه گرمی</h3><div class="price">Loading...</div><div class="currency-symbol">تومان</div></div></div></div>
<script>const apiUrl="https://brsapi.ir/FreeTsetmcBourseApi/Api_Free_Gold_Currency.json";function fetchPrices(){fetch(apiUrl).then(response=>response.json()).then(data=>{const currencies=data.currency,goldPrices=data.gold;const usd=currencies.find(item=>item.name==="دلار");if(usd){document.getElementById("usd").querySelector(".price").innerText=formatPrice(usd.price);}const tty=currencies.find(item=>item.name==="لیر ترکیه");if(tty){document.getElementById("tty").querySelector(".price").innerText=formatPrice(tty.price);}const eur=currencies.find(item=>item.name==="یورو");if(eur){document.getElementById("eur").querySelector(".price").innerText=formatPrice(eur.price);}const goldCoin=goldPrices.find(item=>item.name==="سکه بهار آزادی");if(goldCoin){document.getElementById("gold_coin").querySelector(".price").innerText=formatPrice(goldCoin.price);}const halfCoin=goldPrices.find(item=>item.name==="نیم سکه");if(halfCoin){document.getElementById("half_coin").querySelector(".price").innerText=formatPrice(halfCoin.price);}const quarterCoin=goldPrices.find(item=>item.name==="ربع سکه");if(quarterCoin){document.getElementById("quarter_coin").querySelector(".price").innerText=formatPrice(quarterCoin.price);}const imamiCoin=goldPrices.find(item=>item.name==="سکه امامی");if(imamiCoin){document.getElementById("imami_coin").querySelector(".price").innerText=formatPrice(imamiCoin.price);}const gramCoin=goldPrices.find(item=>item.name==="سکه گرمی");if(gramCoin){document.getElementById("gram_coin").querySelector(".price").innerText=formatPrice(gramCoin.price);}}).catch(error=>{console.error("Error fetching currency data: ",error);document.querySelectorAll(".price").forEach(price=>{price.innerText="خطا در دریافت قیمت";});});}function formatPrice(price){return price.toLocaleString();}window.onload=fetchPrices;setInterval(fetchPrices,180000);let prevScrollpos=window.pageYOffset;window.onscroll=function(){let currentScrollPos=window.pageYOffset;if(prevScrollpos>currentScrollPos){document.getElementById("header").classList.remove("hidden");}else{document.getElementById("header").classList.add("hidden");}prevScrollpos=currentScrollPos;}</script></body></html>
